# Generated by Django 5.1.15 on 2026-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='ingest_stag_source_a45cb6_idx')],
            },
        ),
    ]
