# Generated by Django 5.1.15 on 2026-09-04 11:26

import apps.core.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('national_park', 'National park'), ('state_park', 'State park'), ('monument', 'National monument'), ('forest', 'National forest'), ('other', 'Other')], max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('min_days', models.PositiveSmallIntegerField(default=2)),
                ('vibe_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('nearest_airports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, size=None)),
                ('blurb', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('timed_entry', 'Timed entry'), ('vehicle', 'Vehicle reservation'), ('permit', 'Permit'), ('shuttle', 'Shuttle ticket'), ('lottery', 'Lottery')], max_length=20)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
                ('booking_url', models.URLField(blank=True)),
                ('processing_fee', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rules', to='catalog.spot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('trail', 'Trail'), ('tour', 'Tour')], max_length=10)),
                ('distance_mi', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('elevation_gain_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('permit_required', models.BooleanField(default=False)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalog.spot')),
            ],
        ),
        migrations.CreateModel(
            name='SpotCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('entry_vehicle', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_person', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campsite_low', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campsite_high', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shuttle', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='catalog.spot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='catalog.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='spot',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='catalog.state'),
        ),
        migrations.CreateModel(
            name='VehicleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('max_length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_height_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_weight_lb', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('applies_to_roads', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_limits', to='catalog.spot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriveTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(max_length=4)),
                ('minutes', models.PositiveIntegerField()),
                ('miles', models.DecimalField(decimal_places=1, max_digits=6)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_times', to='catalog.spot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('origin_code', 'spot'), name='unique_drive_time_origin_spot')],
            },
        ),
        migrations.CreateModel(
            name='CrowdIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_indexes', to='catalog.spot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spot', 'month'), name='unique_crowd_index_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='crowd_index_month_range'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='crowd_index_score_range')],
            },
        ),
        migrations.CreateModel(
            name='ClimateNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('high_f', models.DecimalField(decimal_places=1, max_digits=5)),
                ('low_f', models.DecimalField(decimal_places=1, max_digits=5)),
                ('precip_in', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snow_in', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_normals', to='catalog.spot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spot', 'month'), name='unique_climate_normal_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='climate_normal_month_range')],
            },
        ),
    ]
