# Generated by Django 5.1.15 on 2026-09-04 14:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('dump_station', 'Dump station'), ('water', 'Potable water')], max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='catalog.spot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
