# Generated by Django 5.1.15 on 2026-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_spotamenity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='The one photo shown before a visitor opens the gallery.'),
        ),
        migrations.AddField(
            model_name='photo',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='spot',
            name='elevation_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='highlights',
            field=models.TextField(blank=True, help_text='What a visitor will actually see there.'),
        ),
        migrations.AddField(
            model_name='spot',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='spot',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
