# Generated by Django 5.1.15 on 2026-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_photo_options_photo_alt_text_photo_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Official visitor center number.', max_length=20),
        ),
    ]
