# Generated by Django 5.1.15 on 2026-09-04 12:59

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mpg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sleeps', models.PositiveSmallIntegerField()),
                ('included_miles_per_night', models.PositiveIntegerField()),
                ('overage_rate_per_mile', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('base_nightly_rate', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('prep_fee', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('insurance_per_night', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('one_way_fee', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('generator_rate_per_hour', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('hookup_premium_per_night', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='vehicles.vehicleclass')),
            ],
        ),
    ]
