# Generated by Django 5.1.15 on 2026-09-04 12:36

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('campervan', 'Campervan'), ('car', 'Car'), ('hotel', 'Hotel'), ('campsite', 'Campsite'), ('activity', 'Activity'), ('insurance', 'Insurance')], max_length=20)),
                ('base_url', models.URLField()),
                ('tracking_params', models.JSONField(blank=True, default=dict)),
                ('commission_note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.spot')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='partners.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='partners.click')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partners.partner'),
        ),
    ]
