# Generated by Django 5.1.15 on 2026-09-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_manually_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='service_area',
            field=models.CharField(blank=True, help_text="e.g. 'Chicago, IL' — free text, not a Spot.", max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('campervan', 'Campervan'), ('car', 'Car'), ('hotel', 'Hotel'), ('campsite', 'Campsite'), ('activity', 'Activity'), ('insurance', 'Insurance'), ('bicycle', 'Bicycle rental'), ('camping_gear', 'Camping gear rental')], max_length=20),
        ),
    ]
