# Generated by Django 5.1.15 on 2026-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_is_manually_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='terms_note',
            field=models.CharField(blank=True, help_text='One verified real policy detail, not full ToS text.', max_length=300),
        ),
    ]
