# Generated by Django 5.1.15 on 2026-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_contact_phone_partner_terms_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(blank=True, help_text='What this offer actually is, e.g. vehicle sizes.', max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_note',
            field=models.CharField(blank=True, help_text="A real, sourced starting price, e.g. 'From $99/day'.", max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='rating_source',
            field=models.CharField(blank=True, help_text="Where the rating came from, e.g. 'Yelp'.", max_length=40),
        ),
        migrations.AddField(
            model_name='partner',
            name='rating_url',
            field=models.URLField(blank=True, help_text='Link to the rating page — a different source than source_url.'),
        ),
    ]
