# Generated by Django 5.1.15 on 2026-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_offer_description_offer_price_note_partner_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='User-Agent matched a known bot/crawler signature.'),
        ),
    ]
