# Generated by Django 5.1.15 on 2026-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeFreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_manually_verified', models.BooleanField(default=False)),
                ('needs_verification', models.BooleanField(default=False)),
                ('key', models.CharField(choices=[('nonresident_surcharge', 'Non-resident surcharge (per adult)'), ('atb_resident', 'America the Beautiful pass — resident'), ('atb_nonresident', 'America the Beautiful pass — non-resident')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
