# Generated by Django 5.1.15 on 2026-09-04 12:32

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('LEAN', 'Lean'), ('BALANCED', 'Balanced'), ('COMFORT', 'Comfort')], max_length=10)),
                ('total_cost', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_airport', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('budget_usd', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('is_us_resident', models.BooleanField()),
                ('vehicle_pref', models.CharField(choices=[('van', 'Van'), ('car', 'Car')], max_length=10)),
                ('vibe_tags', models.JSONField(blank=True, default=list)),
                ('max_drive_hours_per_day', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('lodging', 'Lodging'), ('entry', 'Entry fees'), ('fuel', 'Fuel'), ('food', 'Food'), ('activities', 'Activities'), ('buffer', 'Buffer')], max_length=20)),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='planner.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='planner.itineraryday')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.spot')),
            ],
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='planner.itinerary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='planner.triprequest'),
        ),
        migrations.AddConstraint(
            model_name='itineraryday',
            constraint=models.UniqueConstraint(fields=('itinerary', 'day_number'), name='unique_itinerary_day_number'),
        ),
    ]
