# Generated by Django 5.1.15 on 2026-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_triprequest_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='total_miles',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
