# Generated by Django 5.1.15 on 2026-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_itinerary_total_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='total_days',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
