# Generated by Django 5.1.15 on 2026-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_itinerary_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Shown on /trips as a curated example itinerary.'),
        ),
    ]
