# Generated by Django 5.1.15 on 2026-09-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_triprequest_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtrip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedtrip',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
