# Generated by Django 5.1.15 on 2026-09-16 12:38

import apps.core.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_savedtrip_user_alter_savedtrip_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='entry_annual_pass_total',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='entry_pass_cheaper',
            field=models.CharField(choices=[('pay_as_you_go', 'Pay as you go'), ('annual_pass', 'Annual pass'), ('tie', 'Tie')], default='pay_as_you_go', max_length=20),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='entry_pass_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='entry_pass_savings',
            field=apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='costline',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('lodging', 'Lodging'), ('entry', 'Entry fees'), ('fuel', 'Fuel'), ('food', 'Food'), ('activities', 'Activities'), ('buffer', 'Buffer'), ('van_base', 'Van — base rate'), ('van_mileage_overage', 'Van — mileage overage'), ('van_prep_fee', 'Van — prep fee'), ('van_insurance', 'Van — insurance'), ('van_one_way_fee', 'Van — one-way fee'), ('van_generator', 'Van — generator'), ('van_hookup_premium', 'Van — hookup premium'), ('van_addons', 'Van — add-ons')], max_length=20),
        ),
    ]
