# Generated by Django 5.1.15 on 2026-09-16 14:14

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_itinerary_entry_annual_pass_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costline',
            name='is_estimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costline',
            name='range_high',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='costline',
            name='range_low',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(help_text="State abbreviation, e.g. 'WY'.", max_length=10)),
                ('month', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('campsite', 'Campsite'), ('motel', 'Motel'), ('car', 'Car rental')], max_length=20)),
                ('low', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('high', apps.core.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('region', 'month', 'category'), name='unique_rate_card_region_month_category')],
            },
        ),
    ]
