# Generated by Django 5.1.15 on 2026-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_costline_is_estimate_costline_range_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='narrative',
            field=models.TextField(blank=True),
        ),
    ]
