# Generated by Django 5.1.15 on 2026-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_itinerary_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=10),
        ),
    ]
